### ISSUE TITLE
update messages keys in UI by scanning minified version of react app

### ISSUE THREAD

**Issue by jagratiTomar** [guigrpa/mady#17]
@guigrpa This is not an issue , but I don't know where to ask this question. So my requirement is to run mady UI in production environment and give the url to the translator so he can update the translations. However, in production I have minified version of my project. So `npm run translate` is not able to find messages from minified chunk.js files. Is there a way to achieve this.

**Comment by guigrpa** [comment]
Maybe you could run mady yourself in development, make it parse the source files, and then deploy to production (including mady), so that the translator can do his work. Of course, tell him not to click on the "refresh" button, lest Mady will mark all messages as unused.

Would this be feasible? (sorry for the long delay, I didn't really know what to answer)
