### ISSUE TITLE
Messageformat 1.0.2 released

### ISSUE THREAD

**Issue by mediafreakch** [guigrpa/mady#7]
Are you planning to update messageformat to 1.0.2?

**Comment by guigrpa** [comment]
In principle, yes. More so, now that I have a large-ish test suite. I hope the API hasn't changed much and there are not many breaking changes!

**Comment by guigrpa** [comment]
Hey, apparently it wasn't that hard. Could you please check out #8? It seems to be OK, but maybe you find some edge cases I haven't considered.

In any case, I will keep on testing this upgrade. I will probably release this as a major upgrade, since I've seen some formatters (e.g. `number`) that seem not to be supported anymore, so this could be a breaking change.

**Comment by mediafreakch** [comment]
Wow that was fast 👍  . I will certainly give it a try. Not sure how useful I am as a tester though, just started using this library...

**Comment by guigrpa** [comment]
OK, I'm merging #8 now since I'm moving over to another issue and want to keep a linear history.

I'm also going to close this, but keep me posted and feel free to re-open if you detect any problem. I couldn't find anything strange during my testing of this upgrade.
